using AIKnowledgeAssistant.Application.Commands.Conversations;
using AIKnowledgeAssistant.Application.Handlers.Conversations;
using AIKnowledgeAssistant.Domain.Entities;
using AIKnowledgeAssistant.Domain.Interfaces;

namespace AIKnowledgeAssistant.Tests.Application.Handlers;

public sealed class CreateConversationCommandHandlerTests
{
    private readonly IConversationRepository _repository = Substitute.For<IConversationRepository>();

    private CreateConversationCommandHandler BuildHandler() => new(_repository);

    [Fact]
    public async Task Handle_ValidCommand_ReturnsResponseWithCorrectTitle()
    {
        var cmd = new CreateConversationCommand(Guid.NewGuid(), "My Chat");

        var response = await BuildHandler().Handle(cmd, CancellationToken.None);

        response.Should().NotBeNull();
        response.Title.Should().Be("My Chat");
        response.Id.Should().NotBeEmpty();
    }

    [Fact]
    public async Task Handle_EmptyTitle_UsesAutoGeneratedTitle()
    {
        var cmd = new CreateConversationCommand(Guid.NewGuid(), string.Empty);

        var response = await BuildHandler().Handle(cmd, CancellationToken.None);

        response.Title.Should().StartWith("Conversation ");
    }

    [Fact]
    public async Task Handle_ValidCommand_CallsAddAsync()
    {
        var cmd = new CreateConversationCommand(Guid.NewGuid(), "Test");

        await BuildHandler().Handle(cmd, CancellationToken.None);

        await _repository.Received(1).AddAsync(Arg.Any<Conversation>(), Arg.Any<CancellationToken>());
    }
}
